Create cpp17.cpp for problem 1001
lightoj-dev/problem-templates pull request #9
Opened 2021-02-13 08:56 UTC by tasfik007

2021-02-18 08:26 UTC, jan876 commented on 1001/cpp17.cpp
> +#include<bits/stdc++.h>
minor spacing: `#include <bits/stdc++.h>`

2021-02-18 08:27 UTC, jan876 commented on 1001/cpp17.cpp
> +vector<int> problemsStored(int n){
C++ styling: use a space before `{`

2021-02-18 08:27 UTC, jan876 commented on 1001/cpp17.cpp
> +int main(){
Same comment as above.

2021-02-18 08:27 UTC, jan876 commented on 1001/cpp17.cpp
> +    int T;
Use qualified names, `cases, caseno`.

2021-02-18 08:29 UTC, jan876 commented on 1001/cpp17.cpp
> +    while(T--){
use a for loop, with `caseno`.

Also, the c++ styling standard wise, use space after while, if, for, etc.

2021-02-18 08:29 UTC, jan876 commented on 1001/cpp17.cpp
> +        printf("%d %d\n",ans[0], ans[1]);
Use space after comma.

2021-02-18 08:29 UTC, jan876 commented on 1001/cpp17.cpp
> +}
Add a newline after the last line.

2021-02-18 08:30 UTC, jan876 requested changes
Thanks a lot. Overall looks good, few minor comments.

2021-02-19 04:54 UTC, tasfik007 commented
Sure, I will make the changes and thanks for the quick feedback.

2021-02-19 05:24 UTC, tasfik007 commented on 1001/cpp17.cpp
> +}
newline added at the end.

2021-02-19 18:00 UTC, jan876 commented
Awesome!

2021-02-19 20:07 UTC, jan876 commented
Merged.

2021-02-19 20:07 UTC, merged